#!/usr/bin/env node
var send = require('./send');
var forever = require('forever');

var command = process.argv[2];

if (command === 'start') {
} else if (command === 'stop') {
} else if (command === 'send') {
}

process.exit();
